# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_SondaMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI_SondaPaginaChamadas import Ui_OtherWindow


class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OtherWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_topology = QtWidgets.QGroupBox(self.centralwidget)
        self.group_topology.setGeometry(QtCore.QRect(50, 30, 221, 311))
        self.group_topology.setObjectName("group_topology")
        self.gridLayoutWidget = QtWidgets.QWidget(self.group_topology)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 131, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_topology = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_topology.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_topology.setObjectName("gridLayout_topology")
        self.UsBackbone = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.UsBackbone.setObjectName("UsBackbone")
        self.gridLayout_topology.addWidget(self.UsBackbone, 8, 0, 1, 1)
        self.Topology1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.Topology1.setObjectName("Topology1")
        self.gridLayout_topology.addWidget(self.Topology1, 3, 0, 1, 1)
        self.German = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.German.setObjectName("German")
        self.gridLayout_topology.addWidget(self.German, 5, 0, 1, 1)
        self.NSFnet = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.NSFnet.setObjectName("NSFnet")
        self.gridLayout_topology.addWidget(self.NSFnet, 6, 0, 1, 1)
        self.European = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.European.setObjectName("European")
        self.gridLayout_topology.addWidget(self.European, 4, 0, 1, 1)
        self.SimpleTopology = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.SimpleTopology.setObjectName("SimpleTopology")
        self.gridLayout_topology.addWidget(self.SimpleTopology, 1, 0, 1, 1)
        self.PacificBell = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.PacificBell.setObjectName("PacificBell")
        self.gridLayout_topology.addWidget(self.PacificBell, 7, 0, 1, 1)
        self.italy_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.italy_radioButton.setObjectName("italy_radioButton")
        self.gridLayout_topology.addWidget(self.italy_radioButton, 11, 0, 1, 1)
        self.Ipe_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.Ipe_radioButton.setObjectName("Ipe_radioButton")
        self.gridLayout_topology.addWidget(self.Ipe_radioButton, 12, 0, 1, 1)
        self.Finland_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.Finland_radioButton.setObjectName("Finland_radioButton")
        self.gridLayout_topology.addWidget(self.Finland_radioButton, 9, 0, 1, 1)
        self.Japan_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.Japan_radioButton.setObjectName("Japan_radioButton")
        self.gridLayout_topology.addWidget(self.Japan_radioButton, 10, 0, 1, 1)
        self.Abilene_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.Abilene_radioButton.setObjectName("Abilene_radioButton")
        self.gridLayout_topology.addWidget(self.Abilene_radioButton, 13, 0, 1, 1)
        self.group_network = QtWidgets.QGroupBox(self.centralwidget)
        self.group_network.setGeometry(QtCore.QRect(50, 520, 221, 101))
        self.group_network.setObjectName("group_network")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.group_network)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 201, 65))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_network = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_network.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_network.setObjectName("gridLayout_network")
        self.EONButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.EONButton.setObjectName("EONButton")
        self.gridLayout_network.addWidget(self.EONButton, 3, 0, 1, 1)
        self.WDMButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.WDMButton.setObjectName("WDMButton")
        self.gridLayout_network.addWidget(self.WDMButton, 2, 0, 1, 1)
        self.fiber_information = QtWidgets.QGroupBox(self.centralwidget)
        self.fiber_information.setGeometry(QtCore.QRect(50, 370, 221, 121))
        self.fiber_information.setObjectName("fiber_information")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.fiber_information)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 121, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_fibers = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_fibers.setContentsMargins(0, 0, 0, 0)
        self.layout_fibers.setObjectName("layout_fibers")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.layout_fibers.addWidget(self.label)
        self.Cores = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Cores.setObjectName("Cores")
        self.layout_fibers.addWidget(self.Cores)
        self.modes = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.modes.setObjectName("modes")
        self.layout_fibers.addWidget(self.modes)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.fiber_information)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 20, 81, 100))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_num_fibers = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_num_fibers.setContentsMargins(0, 0, 0, 0)
        self.layout_num_fibers.setObjectName("layout_num_fibers")
        self.num_fibers = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_fibers.setObjectName("num_fibers")
        self.layout_num_fibers.addWidget(self.num_fibers)
        self.num_cores = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_cores.setObjectName("num_cores")
        self.layout_num_fibers.addWidget(self.num_cores)
        self.num_modes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.num_modes.setObjectName("num_modes")
        self.layout_num_fibers.addWidget(self.num_modes)
        self.load_information = QtWidgets.QGroupBox(self.centralwidget)
        self.load_information.setGeometry(QtCore.QRect(310, 390, 311, 141))
        self.load_information.setObjectName("load_information")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.load_information)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 195, 91))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.layout_load = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.layout_load.setContentsMargins(0, 0, 0, 0)
        self.layout_load.setObjectName("layout_load")
        self.mintrafficload = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.mintrafficload.setObjectName("mintrafficload")
        self.layout_load.addWidget(self.mintrafficload)
        self.maxtrafficload = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.maxtrafficload.setObjectName("maxtrafficload")
        self.layout_load.addWidget(self.maxtrafficload)
        self.step = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.step.setObjectName("step")
        self.layout_load.addWidget(self.step)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.load_information)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(210, 10, 91, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_num_load = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_num_load.setContentsMargins(0, 0, 0, 0)
        self.layout_num_load.setObjectName("layout_num_load")
        self.num_mintl = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.num_mintl.setInputMask("")
        self.num_mintl.setMaxLength(32767)
        self.num_mintl.setObjectName("num_mintl")
        self.layout_num_load.addWidget(self.num_mintl)
        self.num_maxtl = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.num_maxtl.setInputMask("")
        self.num_maxtl.setObjectName("num_maxtl")
        self.layout_num_load.addWidget(self.num_maxtl)
        self.num_step = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.num_step.setInputMask("")
        self.num_step.setObjectName("num_step")
        self.layout_num_load.addWidget(self.num_step)
        self.group_simulation = QtWidgets.QGroupBox(self.centralwidget)
        self.group_simulation.setGeometry(QtCore.QRect(310, 30, 401, 341))
        self.group_simulation.setObjectName("group_simulation")
        self.bloqueios_radioButton = QtWidgets.QRadioButton(self.group_simulation)
        self.bloqueios_radioButton.setGeometry(QtCore.QRect(10, 100, 258, 17))
        self.bloqueios_radioButton.setObjectName("bloqueios_radioButton")
        self.label_4 = QtWidgets.QLabel(self.group_simulation)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 84, 13))
        self.label_4.setObjectName("label_4")
        self.num_calls = QtWidgets.QLineEdit(self.group_simulation)
        self.num_calls.setGeometry(QtCore.QRect(110, 60, 271, 20))
        self.num_calls.setInputMask("")
        self.num_calls.setObjectName("num_calls")
        self.label_5 = QtWidgets.QLabel(self.group_simulation)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_5.setObjectName("label_5")
        self.porcentagem_radioButton = QtWidgets.QRadioButton(self.group_simulation)
        self.porcentagem_radioButton.setGeometry(QtCore.QRect(10, 180, 297, 17))
        self.porcentagem_radioButton.setObjectName("porcentagem_radioButton")
        self.label_6 = QtWidgets.QLabel(self.group_simulation)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.label_6.setObjectName("label_6")
        self.percentual_lineEdit = QtWidgets.QLineEdit(self.group_simulation)
        self.percentual_lineEdit.setGeometry(QtCore.QRect(110, 210, 271, 20))
        self.percentual_lineEdit.setObjectName("percentual_lineEdit")
        self.numbloqueios_lineEdit = QtWidgets.QLineEdit(self.group_simulation)
        self.numbloqueios_lineEdit.setGeometry(QtCore.QRect(110, 130, 271, 20))
        self.numbloqueios_lineEdit.setObjectName("numbloqueios_lineEdit")
        self.chamadas_radioButton = QtWidgets.QRadioButton(self.group_simulation)
        self.chamadas_radioButton.setGeometry(QtCore.QRect(10, 30, 389, 17))
        self.chamadas_radioButton.setObjectName("chamadas_radioButton")
        self.label_9 = QtWidgets.QLabel(self.group_simulation)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 91, 16))
        self.label_9.setObjectName("label_9")
        self.bloqueiopercentual_lineEdit = QtWidgets.QLineEdit(self.group_simulation)
        self.bloqueiopercentual_lineEdit.setGeometry(QtCore.QRect(110, 240, 271, 20))
        self.bloqueiopercentual_lineEdit.setObjectName("bloqueiopercentual_lineEdit")
        self.BER_radioButton = QtWidgets.QRadioButton(self.group_simulation)
        self.BER_radioButton.setGeometry(QtCore.QRect(10, 270, 361, 20))
        self.BER_radioButton.setObjectName("BER_radioButton")
        self.label_10 = QtWidgets.QLabel(self.group_simulation)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 91, 16))
        self.label_10.setObjectName("label_10")
        self.BER_lineEdit = QtWidgets.QLineEdit(self.group_simulation)
        self.BER_lineEdit.setGeometry(QtCore.QRect(110, 300, 271, 20))
        self.BER_lineEdit.setObjectName("BER_lineEdit")
        self.ruidoASE_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ruidoASE_groupBox.setGeometry(QtCore.QRect(620, 390, 91, 141))
        self.ruidoASE_groupBox.setObjectName("ruidoASE_groupBox")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.ruidoASE_groupBox)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(20, 20, 61, 101))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.ruidoASE_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.ruidoASE_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.ruidoASE_verticalLayout.setObjectName("ruidoASE_verticalLayout")
        self.Sim_ruidoASE = QtWidgets.QRadioButton(self.verticalLayoutWidget_9)
        self.Sim_ruidoASE.setObjectName("Sim_ruidoASE")
        self.ruidoASE_verticalLayout.addWidget(self.Sim_ruidoASE)
        self.Nao_ruidoASE = QtWidgets.QRadioButton(self.verticalLayoutWidget_9)
        self.Nao_ruidoASE.setObjectName("Nao_ruidoASE")
        self.ruidoASE_verticalLayout.addWidget(self.Nao_ruidoASE)
        self.amplificadores_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.amplificadores_groupBox.setGeometry(QtCore.QRect(310, 560, 241, 61))
        self.amplificadores_groupBox.setObjectName("amplificadores_groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.amplificadores_groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 20, 171, 22))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.distamplificador_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.distamplificador_label.setObjectName("distamplificador_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distamplificador_label)
        self.dist_amplificador_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dist_amplificador_lineEdit.setEnabled(True)
        self.dist_amplificador_lineEdit.setInputMask("")
        self.dist_amplificador_lineEdit.setMaxLength(32767)
        self.dist_amplificador_lineEdit.setObjectName("dist_amplificador_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dist_amplificador_lineEdit)
        self.result_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.result_groupbox.setGeometry(QtCore.QRect(750, 20, 481, 281))
        self.result_groupbox.setObjectName("result_groupbox")
        self.carga_textBrowser = QtWidgets.QTextBrowser(self.result_groupbox)
        self.carga_textBrowser.setGeometry(QtCore.QRect(20, 50, 441, 151))
        self.carga_textBrowser.setObjectName("carga_textBrowser")
        self.tempo_textBrowser = QtWidgets.QTextBrowser(self.result_groupbox)
        self.tempo_textBrowser.setGeometry(QtCore.QRect(140, 220, 311, 31))
        self.tempo_textBrowser.setObjectName("tempo_textBrowser")
        self.label_2 = QtWidgets.QLabel(self.result_groupbox)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 181, 41))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.result_groupbox)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 167, 31))
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(560, 560, 151, 61))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wavelenght_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.wavelenght_lineEdit.setObjectName("wavelenght_lineEdit")
        self.gridLayout.addWidget(self.wavelenght_lineEdit, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(750, 320, 481, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.SimulateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SimulateButton.setObjectName("SimulateButton")
        self.horizontalLayout.addWidget(self.SimulateButton)
        self.ExitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimulation = QtWidgets.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionSimulation1 = QtWidgets.QAction(MainWindow)
        self.actionSimulation1.setCheckable(True)
        self.actionSimulation1.setChecked(True)
        self.actionSimulation1.setObjectName("actionSimulation1")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_File_as = QtWidgets.QAction(MainWindow)
        self.actionSave_File_as.setObjectName("actionSave_File_as")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionSave_File_as)
        self.menuSimulation.addAction(self.actionSimulation1)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())

        self.SaveButton.clicked.connect(self.openWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_topology.setTitle(_translate("MainWindow", "Topologia:"))
        self.UsBackbone.setText(_translate("MainWindow", "US Backbone"))
        self.Topology1.setText(_translate("MainWindow", "Topology1"))
        self.German.setText(_translate("MainWindow", "German"))
        self.NSFnet.setText(_translate("MainWindow", "NSFnet"))
        self.European.setText(_translate("MainWindow", "European"))
        self.SimpleTopology.setText(_translate("MainWindow", "Simple Topology"))
        self.PacificBell.setText(_translate("MainWindow", "PacificBell"))
        self.italy_radioButton.setText(_translate("MainWindow", "Italy"))
        self.Ipe_radioButton.setText(_translate("MainWindow", "Ipê"))
        self.Finland_radioButton.setText(_translate("MainWindow", "Finland"))
        self.Japan_radioButton.setText(_translate("MainWindow", "Japan"))
        self.Abilene_radioButton.setText(_translate("MainWindow", "Abilene"))
        self.group_network.setTitle(_translate("MainWindow", "Tipo de Rede:"))
        self.EONButton.setText(_translate("MainWindow", "EON "))
        self.WDMButton.setText(_translate("MainWindow", "WDM"))
        self.fiber_information.setTitle(_translate("MainWindow", "Fibras, Núcleos e Modos:"))
        self.label.setText(_translate("MainWindow", "Fibras (1):"))
        self.Cores.setText(_translate("MainWindow", "Núcleos (1):"))
        self.modes.setText(_translate("MainWindow", "Modos (1):"))
        self.num_fibers.setText(_translate("MainWindow", "1"))
        self.num_cores.setText(_translate("MainWindow", "1"))
        self.num_modes.setText(_translate("MainWindow", "1"))
        self.load_information.setTitle(_translate("MainWindow", "Informação da Carga:"))
        self.mintrafficload.setText(_translate("MainWindow", "Carga Min. Tráfego (Erlangs | %):"))
        self.maxtrafficload.setText(_translate("MainWindow", "Carga Máx. Tráfego (Erlangs | %):"))
        self.step.setText(_translate("MainWindow", "Passo Carga de Tráfego (Erlangs | %):"))
        self.group_simulation.setTitle(_translate("MainWindow", "Tipo de simulação:"))
        self.bloqueios_radioButton.setText(_translate("MainWindow", "Variação de carga com número fixo de bloqueios:"))
        self.label_4.setText(_translate("MainWindow", "Nº de Chamadas:"))
        self.label_5.setText(_translate("MainWindow", "Nº de Bloqueios:"))
        self.porcentagem_radioButton.setText(_translate("MainWindow", "Variação percentual na carga de tráfego da rede"))
        self.label_6.setText(_translate("MainWindow", "Carga de Tráfego:"))
        self.chamadas_radioButton.setText(_translate("MainWindow", "Variação de carga de rede com número fixo de chamadas"))
        self.label_9.setText(_translate("MainWindow", "Nº de Chamadas:"))
        self.BER_radioButton.setText(_translate("MainWindow", "Variação BER"))
        self.label_10.setText(_translate("MainWindow", "Nº de Chamadas:"))
        self.ruidoASE_groupBox.setTitle(_translate("MainWindow", "Ruído ASE:"))
        self.Sim_ruidoASE.setText(_translate("MainWindow", "Sim"))
        self.Nao_ruidoASE.setText(_translate("MainWindow", "Não"))
        self.amplificadores_groupBox.setTitle(_translate("MainWindow", "Distância entre os amplificadores de linha:"))
        self.distamplificador_label.setText(_translate("MainWindow", "Km"))
        self.result_groupbox.setTitle(_translate("MainWindow", "Resultado:"))
        self.label_2.setText(_translate("MainWindow", "Carga x Probabilidade de Bloqueio:"))
        self.label_8.setText(_translate("MainWindow", "Tempo de simulação:"))
        self.groupBox.setTitle(_translate("MainWindow", "Para rede WDM, informe:"))
        self.label_7.setText(_translate("MainWindow", "Ghz"))
        self.SaveButton.setText(_translate("MainWindow", "Exibir Resultados Salvos"))
        self.SimulateButton.setText(_translate("MainWindow", "Simular"))
        self.ExitButton.setText(_translate("MainWindow", "Sair"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation"))
        self.actionSave.setText(_translate("MainWindow", "Save File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Save File as"))
        self.actionNew_File.setText(_translate("MainWindow", "Open File"))
        self.actionSimulation1.setText(_translate("MainWindow", "Simulation1"))
        self.actionExit.setText(_translate("MainWindow", "New File"))
        self.actionSave_File_as.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
